export const SET_USERNAME = 'SET_USERNAME';
export const ADD_CHECKLIST = 'ADD_CHECKLIST';
export const REMOVE_CHECKLIST = 'REMOVE_CHECKLIST';
export const ADD_MEMBER = 'ADD_MEMBER';
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
export const EDIT_ANNOUNCEMENT = 'EDIT_ANNOUNCEMENT';
